# -*- coding: utf-8 -*-
"""exp 11. 180 degree rotation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rh04yTNqVvOu13GU9Nvcr84vcOo7TVeF
"""



from PIL import Image
import io
import base64
from IPython.display import display, HTML

# Helper function to create a dummy image if no image is uploaded
def create_dummy_image():
    img = Image.new('RGB', (200, 150), color = 'red')
    from PIL import ImageDraw
    draw = ImageDraw.Draw(img)
    draw.text((50, 60), "Original Image", fill="white")
    return img

# Helper function to display images in HTML side-by-side
def display_images_side_by_side(image1, title1, image2, title2):
    buffered1 = io.BytesIO()
    image1.save(buffered1, format="PNG")
    img_str1 = base64.b64encode(buffered1.getvalue()).decode()

    buffered2 = io.BytesIO()
    image2.save(buffered2, format="PNG")
    img_str2 = base64.b64encode(buffered2.getvalue()).decode()

    html = f"""
    <div style="display: flex; justify-content: space-around;">
        <div style="text-align: center;">
            <h3>{title1}</h3>
            <img src="data:image/png;base64,{img_str1}" style="max-width: 100%; height: auto;">
        </div>
        <div style="text-align: center;">
            <h3>{title2}</h3>
            <img src="data:image/png;base64,{img_str2}" style="max-width: 100%; height: auto;">
        </div>
    </div>
    """
    display(HTML(html))

# Load the specified image file
image_path = '/content/nature image.jpeg'
original_image = Image.open(image_path)

"""### Performing 180-degree rotation clockwise along the y-axis

For a 2D image, a 180-degree rotation along the y-axis is equivalent to a horizontal flip.
"""

# Perform horizontal flip
rotated_image = original_image.transpose(Image.FLIP_LEFT_RIGHT)

# Display the original and rotated images
display_images_side_by_side(original_image, "Original Image", rotated_image, "Rotated Image (180-degree along Y-axis)")