# -*- coding: utf-8 -*-
"""exp 12. 270 degree rotation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XN3xDs5_flfnKpaMK9IM5YuFtkitPpbI
"""



"""Please upload the image file to your Colab environment. You can do this by clicking the folder icon on the left sidebar, then the 'Upload' icon, and selecting your image file."""

from PIL import Image
import matplotlib.pyplot as plt
import os

# Assuming the user uploads an image named 'input_image.jpg'
# You can change 'input_image.jpg' to the actual name of your uploaded file.
image_path = 'nature image.jpeg'

# Check if the file exists before proceeding
if not os.path.exists(image_path):
    print(f"Error: The file '{image_path}' was not found. Please upload the image or specify the correct path.")
else:
    # Load the image
    original_image = Image.open(image_path)

    print("Original Image:")
    plt.imshow(original_image)
    plt.axis('off')
    plt.show()

    # Perform 270-degree clockwise rotation along the y-axis.
    # In 2D image processing, a 270-degree clockwise rotation is equivalent to a 90-degree counter-clockwise rotation.
    rotated_image = original_image.rotate(90, expand=True)

    print("\nImage after 270-degree clockwise rotation:")
    plt.imshow(rotated_image)
    plt.axis('off')
    plt.show()