# -*- coding: utf-8 -*-
"""exp 13.Affine Transformation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkCd2Kp4Jwu8jw_x3mIG9KOBotii3D8E
"""



"""### Affine Transformation

An Affine Transformation is a linear mapping method that preserves lines and parallelism, but not necessarily distances or angles. It can involve operations like scaling, rotation, shear, and translation.

To perform an affine transformation, you need at least three corresponding points between the input image and the desired output image. OpenCV's `cv2.getAffineTransform` function calculates the 2x3 transformation matrix from these points, and `cv2.warpAffine` applies this matrix to the image.
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow # For displaying images in Colab

# --- 1. Load the image ---
# Make sure to upload an image to your Colab environment or provide a valid path.
# For example, you can upload 'my_image.jpg' using the file browser on the left.
image_path = 'nature image.jpeg' # <--- IMPORTANT: Replace with your image path

try:
    img = cv2.imread(image_path)

    if img is None:
        raise FileNotFoundError(f"Image not found at path: {image_path}")

    # Get image dimensions
    rows, cols, ch = img.shape

    # --- 2. Define source and destination points ---
    # For an affine transformation, we need 3 points from the original image
    # and their corresponding 3 points in the transformed image.

    # Source points (top-left, top-right, bottom-left corners as an example)
    # These points will be mapped to the destination points.
    pts1 = np.float32([
        [50, 50],   # Top-left
        [200, 50],  # Top-right
        [50, 200]   # Bottom-left
    ])

    # Destination points (where the source points will move to)
    # This example will scale, rotate, and shear the image slightly.
    pts2 = np.float32([
        [10, 100],  # New position for top-left
        [200, 50],  # New position for top-right
        [100, 250]  # New position for bottom-left
    ])

    # --- 3. Calculate the affine transformation matrix ---
    # This matrix (M) describes how to transform the image.
    M = cv2.getAffineTransform(pts1, pts2)

    # --- 4. Apply the affine transformation ---
    # The third argument (cols, rows) specifies the size of the output image.
    # It's important to ensure this size accommodates the transformed image.
    dst = cv2.warpAffine(img, M, (cols, rows))

    # --- 5. Display the original and transformed images ---
    print("Original Image:")
    cv2_imshow(img)

    print("\nTransformed Image (Affine Transformation):")
    cv2_imshow(dst)

except FileNotFoundError as e:
    print(e)
    print("Please upload an image file (e.g., 'my_image.jpg') or provide a correct path.")
except Exception as e:
    print(f"An error occurred: {e}")